server:
  port: your_port1
datasource:
  driverName: mysql
  host: your_server_ip
  port: your_port2
  database: your_database
  username: root
  password: password
  charset: utf8

redis:
  host: your_server_ip
  port: your_port3
  auth:

