server:
  port: 3344
datasource:
  driverName: mysql
  host: 47.115.213.254
  port: 3310
  database: ginvue
  username: root
  password: 123456
  charset: utf8

redis:
  host: 47.115.213.254
  port: 6379
  auth:

